"""Numerical helpers for reproducing the PEJ paper equations."""

from .core import (
    CamProfile,
    DistillationHistory,
    PiecewiseProfile,
    base_reward,
    cam_radius_from_torque,
    cost_of_transport,
    distill_profile,
    eval_piecewise_profile,
    make_piecewise_profile,
    motor_power,
    offload_percentage,
    paper_tables,
    projected_speed,
    residual_motor_power,
    residual_torque,
    sliding_mean,
    total_reward,
    tracking_error,
)
from .trajectory import (
    REQUIRED_COLUMNS,
    TrajectoryData,
    load_trajectory,
    load_trajectory_csv,
    load_trajectory_npz,
    synthetic_trajectory,
)

__all__ = [
    "REQUIRED_COLUMNS",
    "CamProfile",
    "DistillationHistory",
    "PiecewiseProfile",
    "TrajectoryData",
    "base_reward",
    "cam_radius_from_torque",
    "cost_of_transport",
    "distill_profile",
    "eval_piecewise_profile",
    "load_trajectory",
    "load_trajectory_csv",
    "load_trajectory_npz",
    "make_piecewise_profile",
    "motor_power",
    "offload_percentage",
    "paper_tables",
    "projected_speed",
    "residual_motor_power",
    "residual_torque",
    "sliding_mean",
    "synthetic_trajectory",
    "total_reward",
    "tracking_error",
]
